unit ConfigConversion;

interface
uses
  Profile;

  { Version 0.x: registry -> 1.x: XML }
  function Convert0To1: TProfile;


implementation

function Convert0To1: TProfile;
begin
  Result := nil;



//  FUNCTION_NONE = 0;
//  FUNCTION_OFF = 1;
//  FUNCTION_RED = 2;
//  FUNCTION_AMBER = 3;
//  FUNCTION_GREEN = 4;

{
FUNCTION_PROVIDER_OFFSET = 4

  FUNCTION_FSX_GEAR = FUNCTION_PROVIDER_OFFSET + 1;
  FUNCTION_FSX_LANDINGLIGHTS = FUNCTION_PROVIDER_OFFSET + 2;
  FUNCTION_FSX_INSTRUMENTLIGHTS = FUNCTION_PROVIDER_OFFSET + 3;
  FUNCTION_FSX_PARKINGBRAKE = FUNCTION_PROVIDER_OFFSET + 4;
  FUNCTION_FSX_ENGINE = FUNCTION_PROVIDER_OFFSET + 5;

  FUNCTION_FSX_EXITDOOR = FUNCTION_PROVIDER_OFFSET + 6;
  FUNCTION_FSX_STROBELIGHTS = FUNCTION_PROVIDER_OFFSET + 7;
  FUNCTION_FSX_NAVLIGHTS = FUNCTION_PROVIDER_OFFSET + 8;
  FUNCTION_FSX_BEACONLIGHTS = FUNCTION_PROVIDER_OFFSET + 9;
  FUNCTION_FSX_FLAPS = FUNCTION_PROVIDER_OFFSET + 10;
  FUNCTION_FSX_BATTERYMASTER = FUNCTION_PROVIDER_OFFSET + 11;
  FUNCTION_FSX_AVIONICSMASTER = FUNCTION_PROVIDER_OFFSET + 12;

  FUNCTION_FSX_SPOILERS = FUNCTION_PROVIDER_OFFSET + 13;

  FUNCTION_FSX_PRESSURIZATIONDUMPSWITCH = FUNCTION_PROVIDER_OFFSET + 14;
  FUNCTION_FSX_CARBHEAT = FUNCTION_PROVIDER_OFFSET + 15;
  FUNCTION_FSX_AUTOPILOT = FUNCTION_PROVIDER_OFFSET + 16;
  FUNCTION_FSX_FUELPUMP = FUNCTION_PROVIDER_OFFSET + 17;

  FUNCTION_FSX_TAILHOOK = FUNCTION_PROVIDER_OFFSET + 18;

  FUNCTION_FSX_AUTOPILOT_AMBER = FUNCTION_PROVIDER_OFFSET + 19;
  FUNCTION_FSX_AUTOPILOT_HEADING = FUNCTION_PROVIDER_OFFSET + 20;
  FUNCTION_FSX_AUTOPILOT_APPROACH = FUNCTION_PROVIDER_OFFSET + 21;
  FUNCTION_FSX_AUTOPILOT_BACKCOURSE = FUNCTION_PROVIDER_OFFSET + 22;
  FUNCTION_FSX_AUTOPILOT_ALTITUDE = FUNCTION_PROVIDER_OFFSET + 23;
  FUNCTION_FSX_AUTOPILOT_NAV = FUNCTION_PROVIDER_OFFSET + 24;

  FUNCTION_FSX_TAXILIGHTS = FUNCTION_PROVIDER_OFFSET + 25;
  FUNCTION_FSX_RECOGNITIONLIGHTS = FUNCTION_PROVIDER_OFFSET + 26;
  }
end;

end.
